#ifndef __EBDAT_FEATURE_H__
#define __EBDAT_FEATURE_H__
#define FEATURE_ATCOP_TRECK_SMTP
#define EBDAT_FEAT_SMS
#define EBDAT_FEAT_NETWORK
#define EBDAT_FEAT_GPIO
#define EBDAT_FEAT_GPS
#define EBDAT_FEAT_HD
#define EBDAT_FEAT_AUDIO
#define EBDAT_FEAT_PM
#define EBDAT_FEAT_SPI
#endif /* __EBDAT_FEATURE_H__*/