#ifndef __EBDAT_FUNC_ARY_ID_H__
#define __EBDAT_FUNC_ARY_ID_H__

#include "ebdat_types.h"

#ifdef FEATURE_SIMCOM_EMBEDDED_AT

typedef enum ebdat_func_id_e{
IDF_strcpy = 0,
IDF_strlen,
IDF_strncpy,
IDF_strcat,
IDF_strncat,
IDF_strstr,
IDF_strcmp,
IDF_strncmp,
IDF_sprintf,
IDF_std_strlcpy,
IDF_std_strlcat,
IDF_std_strlprintf,
IDF_sscanf,
IDF_itoa,
IDF_atoi,
IDF_vsprintf,
IDF_vsnprintf,

IDF_memcpy=30,
IDF_memchr,
IDF_memcmp,
IDF_memmove,
IDF_memset,
IDF_setjmp,
IDF_longjmp,

IDF_ebdat_os_printdir =50,
IDF_ebdat_os_print,
IDF_ebdat_os_get_tick,
IDF_ebdat_os_mktime,
IDF_ebdat_os_localtime,
IDF_ebdat_os_gmtime,
IDF_ebdat_os_strftime,
IDF_ebdat_os_mem_alloc,
IDF_ebdat_os_mem_realloc,
IDF_ebdat_os_mem_free,
IDF_ebdat_os_autodog,
IDF_ebdat_os_assert_okts,
IDF_ebdat_os_negate_okts,
IDF_ebdat_os_get_usb_mode,
IDF_ebdat_os_set_portmode,
IDF_ebdat_os_get_portmode,
IDF_ebdat_os_time,

IDF_ebdat_set_evt = 80,
IDF_ebdat_wait_evt,
IDF_ebdat_peek_evt,
IDF_ebdat_clear_evts,
IDF_ebdat_evt_get_evt_priority,
IDF_ebdat_evt_set_evt_priority,
IDF_ebdat_evt_set_evt_owner_thread_idx,
IDF_ebdat_evt_get_evt_owner_thread_idx,
IDF_ebdat_evt_set_evt_as_ignored,
IDF_ebdat_evt_is_evt_ignored,
IDF_ebdat_delete_spec_evt_with_params_from_queue,
IDF_ebdat_get_evt_count_in_queue,
IDF_ebdat_evt_filter_add,
IDF_ebdat_evt_filter_delete,

IDF_ebdat_set_current_thread_priority = 110,
IDF_ebdat_set_thread_priority,
IDF_ebdat_get_current_thread_priority,
IDF_ebdat_get_thread_priority,
IDF_ebdat_enter_crit_sect,
IDF_ebdat_leave_crit_sect,
IDF_ebdat_thread_sleep,
IDF_ebdat_create_thread,
IDF_ebdat_kill_thread,
IDF_ebdat_resume_thread,
IDF_ebdat_suspend_thread,
IDF_ebdat_thread_running,
IDF_ebdat_thread_suspended,
IDF_ebdat_thread_get_current_index,
IDF_ebdat_thread_register_prekill_func,
IDF_ebdat_signal_clean,
IDF_ebdat_signal_notify,
IDF_ebdat_signal_wait,
//timer & sio
IDF_ebdat_starttimer = 140,
IDF_ebdat_stoptimer,
IDF_ebdat_stopalltimer_for_thread,
IDF_ebdat_stopalltimer,
IDF_ebdat_sio_send,
IDF_ebdat_sio_recv,
IDF_ebdat_sio_exclrpt,
IDF_ebdat_sio_enable_recv,
IDF_ebdat_sio_clear,
IDF_ebdat_sio_set_rcvcache_size,
IDF_ebdat_sio_get_rcvcache_size,
//efs
IDF_ebdat_efs_creat = 160,
IDF_ebdat_efs_open,
IDF_ebdat_efs_close,
IDF_ebdat_efs_read,
IDF_ebdat_efs_write,
IDF_ebdat_efs_ftruncate,
IDF_ebdat_efs_lseek,
IDF_ebdat_efs_stat,
IDF_ebdat_efs_fstat,
IDF_ebdat_efs_lstat,
IDF_ebdat_efs_tell,
IDF_ebdat_efs_get_opened_filesize,
IDF_ebdat_efs_file_exist,
IDF_ebdat_efs_dir_exist,
IDF_ebdat_efs_delete_file,
IDF_ebdat_efs_rmdir,
IDF_ebdat_efs_mkdir,
IDF_ebdat_efs_get_filesize,
IDF_ebdat_efs_truncate_file,
IDF_ebdat_efs_lsdir,
IDF_ebdat_efs_lsfile,
//ftp
IDF_ebdat_ftp_simpput = 200,
IDF_ebdat_ftp_simpget,
IDF_ebdat_ftp_simplist,
//mms
IDF_ebdat_mms_accquire_module = 220,
IDF_ebdat_mms_release_module,
IDF_ebdat_mms_set_mmsc,
IDF_ebdat_mms_get_mmsc,
IDF_ebdat_mms_set_protocol,
IDF_ebdat_mms_get_protocol,
IDF_ebdat_mms_set_edit,
IDF_ebdat_mms_set_title,
IDF_ebdat_mms_get_title,
IDF_ebdat_mms_attach_file,
IDF_ebdat_mms_attach_file_from_memory,
IDF_ebdat_mms_add_receipt,
IDF_ebdat_mms_delete_receipt,
IDF_ebdat_mms_list_receipts,
IDF_ebdat_mms_save_attachment,
IDF_ebdat_mms_save,
IDF_ebdat_mms_load,
IDF_ebdat_mms_get_attach_info,
IDF_ebdat_mms_list_attach_info,
IDF_ebdat_mms_get_delivery_date_info,
IDF_ebdat_mms_read_attachment,
IDF_ebdat_mms_send,
IDF_ebdat_mms_recv,
//sms
#ifdef EBDAT_FEAT_SMS
IDF_ebdat_sms_get_cmgf = 260,
IDF_ebdat_sms_set_cmgf,
IDF_ebdat_sms_get_cscs,
IDF_ebdat_sms_set_cscs,
IDF_ebdat_sms_get_next_msg_ref,
IDF_ebdat_sms_convert_chset,
IDF_ebdat_sms_send_smstxt_msg,
IDF_ebdat_sms_write_smstxt_msg,
IDF_ebdat_sms_decode_pdu_sms,
IDF_ebdat_sms_cmss,
IDF_ebdat_sms_read_msg,
#endif /* EBDAT_FEAT_SMS */
//smtp
IDF_ebdat_smtp_config = 290,
IDF_ebdat_smtp_set_from,
IDF_ebdat_smtp_set_rcpt,
IDF_ebdat_smtp_set_subject,
IDF_ebdat_smtp_set_body_charset,
IDF_ebdat_smtp_set_body,
IDF_ebdat_smtp_set_file,
IDF_ebdat_smtp_send,
//network
#ifdef EBDAT_FEAT_NETWORK
IDF_ebdat_network_get_creg = 310,
IDF_ebdat_network_get_cgreg,
IDF_ebdat_network_get_cnsmod,
IDF_ebdat_network_get_csq,
#endif /* EBDAT_FEAT_NETWORK */
//atctl
IDF_ebdat_atctl_send = 330,
IDF_ebdat_atctl_recv,
IDF_ebdat_atctl_setport,
IDF_ebdat_atctl_clear,
//gps
#ifdef EBDAT_FEAT_GPS
IDF_ebdat_gps_start = 350,
IDF_ebdat_gps_stop,
IDF_ebdat_gps_get_fix_info,
IDF_ebdat_gps_get_nmea_info,
IDF_ebdat_gps_set_mode,
IDF_ebdat_gps_get_mode,
IDF_ebdat_gps_delete_info,
#endif /* EBDAT_FEAT_GPS */
//gpio
#ifdef EBDAT_FEAT_GPIO
IDF_ebdat_gpio_config = 370,
IDF_ebdat_gpio_out,
IDF_ebdat_gpio_get,
IDF_ebdat_gpio_func_set,
IDF_ebdat_gpio_isr_set,
IDF_ebdat_gpio_debounce_set,
#endif /* EBDAT_FEAT_GPIO */
//spi
#ifdef EBDAT_FEAT_SPI
IDF_ebdat_spi_init = 390,
IDF_ebdat_spi_set_clk_info,
IDF_ebdat_spi_set_cs,
IDF_ebdat_spi_set_frequency,
IDF_ebdat_spi_set_param,
IDF_ebdat_spi_write_data,
IDF_ebdat_spi_write_uint32_data,
IDF_ebdat_spi_write_reg,
IDF_ebdat_spi_read_reg,
#endif /* EBDAT_FEAT_SPI */
//hd
#ifdef EBDAT_FEAT_HD
IDF_ebdat_adc_read = 420,
IDF_ebdat_vaux_set,
IDF_ebdat_vaux_get,
IDF_ebdat_vaux_switch,
IDF_ebdat_vaux_get_state,
IDF_ebdat_i2c_read,
IDF_ebdat_i2c_combined_write_read,
IDF_ebdat_i2c_write,
#endif /* EBDAT_FEAT_HD */
//pm
#ifdef EBDAT_FEAT_PM
IDF_ebdat_pm_auto_pwr_off_set = 440,
IDF_ebdat_pm_auto_pwr_off_get,
IDF_ebdat_pm_enable_low_voltage_alarm,
IDF_ebdat_pm_disable_low_voltage_alarm,
IDF_ebdat_pm_enable_auto_pwr_on,
IDF_ebdat_pm_disable_auto_pwr_on,
IDF_ebdat_pm_enable_auto_pwr_off,
IDF_ebdat_pm_disable_auto_pwr_off,
IDF_ebdat_pm_power_off,
IDF_ebdat_pm_power_reset,
#endif /* EBDAT_FEAT_PM */
//audio
#ifdef EBDAT_FEAT_AUDIO
IDF_ebdat_audio_mic_gain_set = 460,
IDF_ebdat_audio_sidetone_set,
IDF_ebdat_auido_tx_gain_set,
IDF_ebdat_audio_rx_gain_set,
IDF_ebdat_audio_tx_vol_set,
IDF_ebdat_audio_rx_vol_set,
IDF_ebdat_audio_tx_ftr_set,
IDF_ebdat_audio_rx_ftr_set,
IDF_ebdat_audio_echo_mode_set,
IDF_ebdat_audio_noise_mode_set,
IDF_ebdat_audio_echo_param_set,
IDF_ebdat_audio_volumn_level_set,
IDF_ebdat_audio_volumn_level_select,
IDF_ebdat_audio_device_set,
IDF_ebdat_audio_device_mute,
IDF_ebdat_audio_pcm_set,
IDF_ebdat_audio_play_tone,
#endif /* EBDAT_FEAT_AUDIO */
//socket
IDF_ebdat_ps_open_ps_network = 500,
IDF_ebdat_ps_close_ps_network,
IDF_ebdat_ps_release_ps_netlib,
IDF_ebdat_sock_async_deselect,
IDF_ebdat_sock_async_select,
IDF_ebdat_sock_create,
IDF_ebdat_sock_connect,
IDF_ebdat_sock_recv,
IDF_ebdat_sock_send,
IDF_ebdat_sock_recvfrom,
IDF_ebdat_sock_sendto,
IDF_ebdat_sock_close,
IDF_ebdat_sock_bind,
IDF_ebdat_sock_listen,
IDF_ebdat_sock_accept,
IDF_ebdat_sock_setsockopt,
IDF_ebdat_sock_getsockopt,
IDF_ebdat_sock_get_sock_name,
IDF_ebdat_dns_get_host_entry,

IDF_srand = 550,
IDF_rand,
IDF_qsort,
IDF_atof,
IDF_fabs,
IDF_sin,
IDF_sinh,
IDF_cos,
IDF_cosh,
IDF_tan,
IDF_tanh,
IDF_asin,
IDF_acos,
IDF_atan,
IDF_atan2,
IDF_ceil,
IDF_floor,
IDF_fmod,
IDF_modf,
IDF_sqrt,
IDF_log,
IDF_log10,
IDF_exp,
IDF_frexp,
IDF_ldexp,
IDF_bsearch,
//hash
IDF_ebdat_md5_Init = 590,
IDF_ebdat_md5_update,
IDF_ebdat_md5_final,
IDF_ebdat_sha1_init,
IDF_ebdat_sha1_update,
IDF_ebdat_sha1_final,
IDF_ebdat_sha256_init,
IDF_ebdat_sha256_update,
IDF_ebdat_sha256_final,
IDF_ebdat_sha384_init,
IDF_ebdat_sha384_update,
IDF_ebdat_sha384_final,
IDF_ebdat_sha512_init,
IDF_ebdat_sha512_update,
IDF_ebdat_sha512_final,
//minizip
IDF_ebdat_minizip_openzip = 620,
IDF_ebdat_minizip_add_file,
IDF_ebdat_minizip_closezip,
IDF_ebdat_miniunz_openzip,
IDF_ebdat_miniunz_closezip,
IDF_ebdat_miniunz_get_entry_count,
IDF_ebdat_miniunz_get_current_file_info,
IDF_ebdat_miniunz_goto_next_file,
IDF_ebdat_miniunz_extract_currentfile,
//lua
IDF_ebdat_lua_register_api_handler = 640,
IDF_ebdat_lua_deregister_api_handler,
IDF_ebdat_lua_set_evt,
IDF_ebdat_lua_signal_notify,
IDF_ebdat_lua_set_ready,

IDF_ebdat_func_max = 1024
}ebdat_func_id_e_type;
#endif /* FEATURE_SIMCOM_EMBEDDED_AT */
#endif /* __EBDAT_FUNC_ARY_ID_H__ */